"""init

Revision ID: 62bfc32ca81b
Revises: 
Create Date: 2026-03-28 19:32:26.498217+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bfc32ca81b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('category_name', sa.String(length=64), nullable=True, comment='分类名（冗余）'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('summary', sa.String(length=512), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='Markdown 内容'),
    sa.Column('html_content', sa.Text(), nullable=True, comment='富文本内容'),
    sa.Column('cover', sa.String(length=512), nullable=True, comment='封面图片'),
    sa.Column('original', sa.SmallInteger(), nullable=False, comment='是否原创：1是 0否'),
    sa.Column('reproduce', sa.String(length=512), nullable=True, comment='转载地址'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数（冗余）'),
    sa.Column('collect_count', sa.Integer(), nullable=False, comment='收藏数（冗余）'),
    sa.Column('comment_count', sa.Integer(), nullable=False, comment='评论数（冗余）'),
    sa.Column('is_recommend', sa.SmallInteger(), nullable=False, comment='是否推荐：1是 0否'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除：1是 0否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('name', sa.String(length=64), nullable=False, comment='分类名'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除：1是 0否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client',
    sa.Column('name', sa.String(length=128), nullable=False, comment='客户端名称'),
    sa.Column('client_id', sa.String(length=64), nullable=False, comment='客户端ID（自动生成）'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('collect',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='收藏时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('from_user_id', sa.Integer(), nullable=False, comment='评论者ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('comment_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='评论时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除：1是 0否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_link',
    sa.Column('name', sa.String(length=64), nullable=False, comment='博客名称'),
    sa.Column('url', sa.String(length=512), nullable=False, comment='链接'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像（icon）'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='简介'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('pid', sa.Integer(), nullable=True, comment='父ID，留言时为null'),
    sa.Column('from_user_id', sa.Integer(), nullable=False, comment='留言/回复者ID'),
    sa.Column('to_user_id', sa.Integer(), nullable=True, comment='被回复者ID，留言时为null'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除：1是 0否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('comment_id', sa.Integer(), nullable=False, comment='所属评论ID'),
    sa.Column('from_user_id', sa.Integer(), nullable=False, comment='回复者ID'),
    sa.Column('to_user_id', sa.Integer(), nullable=True, comment='被回复者ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='回复内容'),
    sa.Column('reply_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='回复时间'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除：1是 0否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=64), nullable=False, comment='标签名'),
    sa.Column('deleted', sa.SmallInteger(), nullable=False, comment='是否删除：1是 0否'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码（bcrypt）'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别：1男 0女'),
    sa.Column('birthday', sa.String(length=20), nullable=True, comment='生日'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('brief', sa.String(length=256), nullable=True, comment='个性签名'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像路径（MinIO key）'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态'),
    sa.Column('admin', sa.SmallInteger(), nullable=False, comment='是否管理员'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('reply')
    op.drop_table('message')
    op.drop_table('like')
    op.drop_table('friend_link')
    op.drop_table('comment')
    op.drop_table('collect')
    op.drop_table('client')
    op.drop_table('category')
    op.drop_table('article_tag')
    op.drop_table('article')
    # ### end Alembic commands ###
