"""second

Revision ID: f9863d6375a9
Revises: 62bfc32ca81b
Create Date: 2026-03-29 04:18:42.959542+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9863d6375a9'
down_revision: Union[str, Sequence[str], None] = '62bfc32ca81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'deleted')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.SMALLINT(), autoincrement=False, nullable=True, comment='性别：1男 0女'))
    op.add_column('user', sa.Column('birthday', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='生日'))
    op.add_column('tag', sa.Column('deleted', sa.SMALLINT(), autoincrement=False, nullable=False, comment='是否删除：1是 0否'))
    # ### end Alembic commands ###
