"""third

Revision ID: 1f0ac3dc6d8c
Revises: f9863d6375a9
Create Date: 2026-03-29 12:38:31.303743+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f0ac3dc6d8c"
down_revision: Union[str, Sequence[str], None] = "f9863d6375a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "last_login_at", sa.DateTime(timezone=True), nullable=True, comment="最后登录时间"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login_at")
    # ### end Alembic commands ###
